return {
  'm4xshen/hardtime.nvim',
  lazy = false,
  dependencies = { 'MunifTanjim/nui.nvim' },
  opts = {
    max_time = 1000,
    max_count = 5,
    disable_mouse = false,
    hint = true,
    timeout = 3000,
    notification = true,
    allow_different_key = true,
    enabled = true,
    force_exit_insert_mode = false,
    max_insert_idle_ms = 5000,
    resetting_keys = {
      ['1'] = { 'n', 'x' },
      ['2'] = { 'n', 'x' },
      ['3'] = { 'n', 'x' },
      ['4'] = { 'n', 'x' },
      ['5'] = { 'n', 'x' },
      ['6'] = { 'n', 'x' },
      ['7'] = { 'n', 'x' },
      ['8'] = { 'n', 'x' },
      ['9'] = { 'n', 'x' },
      ['c'] = { 'n' },
      ['C'] = { 'n' },
      ['d'] = { 'n' },
      ['x'] = { 'n' },
      ['X'] = { 'n' },
      ['y'] = { 'n' },
      ['Y'] = { 'n' },
      ['p'] = { 'n' },
      ['P'] = { 'n' },
      ['gp'] = { 'n' },
      ['gP'] = { 'n' },
      ['.'] = { 'n' },
      ['='] = { 'n' },
      ['<'] = { 'n' },
      ['>'] = { 'n' },
      ['J'] = { 'n' },
      ['gJ'] = { 'n' },
      ['~'] = { 'n' },
      ['g~'] = { 'n' },
      ['gu'] = { 'n' },
      ['gU'] = { 'n' },
      ['gq'] = { 'n' },
      ['gw'] = { 'n' },
      ['g?'] = { 'n' },
      ['<C-N>'] = { 'n' },
    },
    restriction_mode = 'hint', -- block or hint
    restricted_keys = {
      ['h'] = { 'n', 'x' },
      ['j'] = { 'n', 'x' },
      ['k'] = { 'n', 'x' },
      ['l'] = { 'n', 'x' },
      ['+'] = { 'n', 'x' },
      ['gj'] = { 'n', 'x' },
      ['gk'] = { 'n', 'x' },
      ['<C-M>'] = { 'n', 'x' },
      ['<C-P>'] = { 'n', 'x' },
    },
    disabled_keys = {
      ['<Up>'] = false,
      ['<Down>'] = false,
      ['<Left>'] = false,
      ['<Right>'] = false,
    },
    disabled_filetypes = {
      ['aerial'] = true,
      ['alpha'] = true,
      ['Avante'] = true,
      ['checkhealth'] = true,
      ['dapui.*'] = true,
      ['db.*'] = true,
      ['Diffview.*'] = true,
      ['Dressing.*'] = true,
      ['fugitive'] = true,
      ['help'] = true,
      ['httpResult'] = true,
      ['lazy'] = true,
      ['lspinfo'] = true,
      ['mason'] = true,
      ['minifiles'] = true,
      ['Neogit.*'] = true,
      ['neo%-tree.*'] = true,
      ['neotest%-summary'] = true,
      ['netrw'] = true,
      ['noice'] = true,
      ['notify'] = true,
      ['NvimTree'] = true,
      ['oil'] = true,
      ['prompt'] = true,
      ['qf'] = true,
      ['query'] = true,
      ['snacks_dashboard'] = true,
      ['TelescopePrompt'] = true,
      ['Trouble'] = true,
      ['trouble'] = true,
      ['VoltWindow'] = true,
      ['undotree'] = true,
      ['compilation'] = true,
    },
    ui = {
      enter = true,
      focusable = true,
      border = {
        style = 'rounded',
        text = {
          top = 'Hardtime Report',
          top_align = 'center',
        },
      },
      position = '50%',
      size = {
        width = '40%',
        height = '60%',
      },
    },
  },
}
